### ISSUE TITLE
ARM build fails

### ISSUE THREAD

**Issue by mzealey** [tokenrove/granderl#13]
The `rdrand`/`rdtsc` functions are only implemented on amd64 architectures which means building this on other architectures (eg arm64) is impossible unfortunately. Is there any way to build a generic work around?

```
#25 859.8 In file included from ./c_src/pcg32.c:35:
#25 859.8 ./c_src/rdtsc.h:11:2: error: #error "Read your platform's perf counter here"
#25 859.8    11 | #error "Read your platform's perf counter here"
#25 859.8       |  ^~~~~
#25 859.8 ./c_src/pcg32.c: In function 'uniform32':
#25 859.8 ./c_src/pcg32.c:47:9: warning: implicit declaration of function 'rdtsc' [-Wimplicit-function-declaration]
#25 859.8    47 |         rdtsc(&state, &u);
#25 859.8       |         ^~~~~
#25 860.7 ===> Hook for compile failed!
#25 860.7 
```

**Comment by tokenrove** [comment]
Sure.  We could read the PMC on ARM directly, but I seem to recall this is just used for seeding, so probably we should just call `clock_gettime(CLOCK_MONOTONIC_RAW)` at least on Linux.  Note that this library is already a bit unsafe and was only ever tuned for x86-64, but if you're willing to test a change, I'm willing to make a patch.  If you're looking for macOS support, I'm not sure what the right interface is for this, but I guess I can figure it out.

**Comment by tokenrove** [comment]
Let me know if #14 works for you.

**Comment by mzealey** [comment]
Thanks for the quick response! I'm actually only using this library via `statsderl` via `shackle`, so I think it's highly unlikely that this code-path gets hit (ie I don't have any real way of testing the functionality) but as it's failing at compile-time at present I'll try a few compiles with this and get back to you, probably tomorrow to see if it fixes the issue that I'm running in to.

**Comment by mzealey** [comment]
So for my use-case, this patch is working great. However as I mentioned above I believe I'm only testing the build side rather than any aspect of the functionality.
