### ISSUE TITLE
Switch from Travis-CI to Github Actions

### ISSUE THREAD

**Issue by lpgauth** [tokenrove/granderl#19]
Hey Julian,
I tried switching from Travis to GA, but unfortunately `Dieharder` doesn't build with a recent `gcc`.

https://github.com/lpgauth/granderl/actions/runs/4901400662/jobs/8752648865#step:5:147

I found a few forks on Github but I figured I checked with you if you had a fork you preferred?

**Comment by tokenrove** [comment]
Hey, sorry for the delay here -- I've been sick all week :-/

I took a quick look through the change history of a couple of the forks and https://github.com/eddelbuettel/dieharder looks reasonable and seems to build in GHA.  I can take care of this if you want but if you already have something almost working, I'd be thrilled to not have to bother with this myself.  Thanks.

**Comment by tokenrove** [comment]
Closed by #20
