### ISSUE TITLE
Not working on OSX

### ISSUE THREAD

**Issue by silviucpp** [tokenrove/granderl#2]
c_src/rdrand.h:14:2: error: "A platform with rdrand support is required"
# error "A platform with rdrand support is required"

 ^
/Users/silviu.caragea/Desktop/projects/beanstalked/deps/granderl/c_src/rdrand.c:19:18: warning: implicit declaration of function 'rdrand64' is invalid in C99 [-Wimplicit-function-declaration]
    uint64_t t = rdrand64();
                 ^
1 warning and 1 error generated.

Silviu

**Comment by tokenrove** [comment]
Odd.  This was tested on OS X recently, but perhaps only on a machine with rdrand.

If you run the following in your shell from the `granderl` directory, what do you get?

```
gcc -o build/test_for_rdrand c_src/test_for_rdrand.c && ./build/test_for_rdrand; echo $?
```

Thanks!

**Comment by shlokspeare** [comment]
getting same error, my output
`[test_server] Shlok@~/ser/oyeok_server/api$ gcc -o build/test_for_rdrand c_src/test_for_rdrand.c && ./build/test_for_rdrand; echo $?`
clang: error: no such file or directory: 'c_src/test_for_rdrand.c'
clang: error: no input files
1

**Comment by shlokspeare** [comment]
Getting same error, went into my deps directory of granderl.
[test_server] Shlok@~/ser/oyeok_server/api/deps$ cd granderl

[(HEAD detached at v0.1.1)] Shlok@~/ser/oyeok_server/api/deps/granderl$ gcc -o build/test_for_rdrand c_src/test_for_rdrand.c && ./build/test_for_rdrand; echo $?

`ld: can't open output file for writing: build/test_for_rdrand, errno=2 for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
1`

**Comment by shlokspeare** [comment]
When i do with -v,

`Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.11.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -main-file-name test_for_rdrand.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 253.6 -v -dwarf-column-info -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.0 -fdebug-compilation-dir /Users/home/ser/oyeok_server/api/deps/granderl -ferror-limit 19 -fmessage-length 132 -stack-protector 1 -mstackrealign -fblocks -fobjc-runtime=macosx-10.11.0 -fencode-extended-block-signature -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/0c/ptzcyz1168g7m77khphggzpc0000gn/T/test_for_rdrand-7d164f.o -x c c_src/test_for_rdrand.c
clang -cc1 version 7.0.0 based upon LLVM 3.7.0svn default target x86_64-apple-darwin15.5.0
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -dynamic -arch x86_64 -macosx_version_min 10.11.0 -o build/test_for_rdrand /var/folders/0c/ptzcyz1168g7m77khphggzpc0000gn/T/test_for_rdrand-7d164f.o -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.0/lib/darwin/libclang_rt.osx.a
ld: can't open output file for writing: build/test_for_rdrand, errno=2 for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
1`

**Comment by tokenrove** [comment]
Hmm, the fact that build isn't there makes me wonder: are you building this with rebar or rebar3?  If you're building it with rebar, it probably won't work.  If you're building it with rebar3, perhaps something is going wrong with how it invokes the build.

My previous invocation should have read:

```
mkdir build && gcc -o build/test_for_rdrand c_src/test_for_rdrand.c && ./build/test_for_rdrand; echo $?
```

Try that from within the granderl directory and let me know what the output is.

Thanks.

**Comment by shlokspeare** [comment]
It is with rebar, not rebar3! Oops. Is there a legacy branch compatible with rebar?

**Comment by tokenrove** [comment]
No, sorry.  I can look into making it compatible if you'd like (mostly means making the build behave the way the old port compiler expected), although I understood that rebar is considered deprecated at this point.  I'm going to close this issue, but if you'd like legacy rebar support, feel free to open another issue called "Support legacy rebar".
